---
title: "Academic and Professional Experience"
---

\

## Education

***

**Columbia University Mailman School of Public Health, New York, NY**

Master of Public Health, Epidemiology/Certificate in Molecular Epidemiology, Expected May 2021.

* GPA: 4.00/4.00. Merit-based Scholarship.


**University of California Los Angeles, Los Angeles, CA**

Bachelor of Science, Molecular, Cell, and Developmental Biology, March 2019.	 

* GPA: 3.92/4.00. Bioinformatics Minor. Summa Cum Laude. Phi Beta Kappa.

\

## Research / Work Experience

***

**Mailman School of Public Health, Columbia University**			

**_Researcher_**

New York, September 2020-Present

* Developing a Master’s thesis aimed to investigate patterns of use for third-line Regorafenib and TAS-102 among older patients with colorectal cancer through analysis of the Surveillance, Epidemiology, and End Results-Medicare (SEER-Medicare) linked dataset using SAS

\

**Kendall Capital Partners**

**_Venture Capital Analyst, Intern_**

Boston, September 2020-Present

* Sourced deals and supported investors to evaluate potential investments in early-stage companies incubated by scientific labs from top universities; conducted due diligence assessment for three companies

* Wrote an industry research report on TCR-T immunotherapy

\

**Real World Solutions, IQVIA**

**_Part-Time Assistant_**

Shanghai, China, Summer 2020

*	Conducted a literature review on real-world data sources in China within the scope of 6 non-oncology disease areas; screened over 700 publications in 5 days

*	Performed desk research and collected data and information needed for cost-effectiveness analyses

*	Wrote interview notes and used EXCEL to input, organize, and clean data extracted from interviews with experts about hospital resource utilization and costs

*	Assisted consultants to prepare project report in the form of PowerPoint decks

\

**COVID-19 Task Force, U.S.–China Health Summit**	 

**_Research Project Lead, Volunteer_**

New York, February 2020-Present

*	Initiated and led three projects aimed to assess benefits and challenges of applying an innovative clinical trial design, Master Protocol, for promotion of its use worldwide; final products included a literature review, a policy recommendation paper, and a cost estimation paper

*	Reached and interviewed 4 experts on Master Protocol from academia and industry

*	Responsible for developing a protocol to estimate pivotal trial costs based on Master Protocol design and compared those with traditional trial costs using public data sources and cost estimation tools

*	Conducted desk research, provided Chinese policymakers with information of COVID-19 mutation and evolution, and suggested medical countermeasures for diagnosis, treatment, and vaccine when China was the epicenter

\

**Fogel Laboratory, Department of Neurology, UCLA**                             

**_Undergraduate Researcher_**	

Los Angeles, CA, Summer 2017-Spring 2019

*	Designed and conducted an improved spinocerebellar ataxia 37 (SCA37) diagnostic protocol in a UCLA patient cohort of 596 patients including data analysis of DNA samples

*	Analyzed gene copy number variation of exome data from undiagnosed SCA patients using VarSeq

*	Conducted an SCA36 repeat expansion testing project in a UCLA cohort of 89 patients

*	Contributed to and edited manuscripts for publication (see publications section below)

\

**Shanghai Institute of Medical Genetics**

**_Research Assistant_**

Shanghai, China, Summer 2018

*	Formulated experiment schedules for a research study to establish a minicircle DNA vector system for gene therapy; presented project progresses to the researchers and employees at institute meetings

*	Practiced experimental techniques and accurately followed research protocols including restriction enzyme digestion, molecular cloning, cell transfection, and flow cytometry

\

**CloudHealth Genomics**          

**_Research Intern_**

Shanghai, China, Summer 2016

*	Hands-on experience with Illumina sequencing, sequence alignment, and human genome analysis

\

## Publications

***

* Syriani, D. A., Wong, D., Andani, S., De Gusmao, C. M., **Mao, Y.**, Sanyoura, M., ... & Gomez, C. M. (2020). Prevalence of RFC1-mediated spinocerebellar ataxia in a North American ataxia cohort. _Neurology Genetics,_ 6(3).

*	Ngo, K.J., Rexach, J.E., Lee, H., Petty, L.E., Perlman, S., Valera, J.M., Deignan, J.L., **Mao, Y.**, Aker, M., Posey, J.E. and Jhangiani, S.N. (2019). A diagnostic ceiling for exome sequencing in cerebellar ataxia and related neurological disorders. _Human Mutation,_ 41(2), 487-501.

\

## Leadership

***

**_President,_** Columbia University Plus86 Dance Team (December 2019-Present). 

**_Team Captain,_** UCLA CSSA Modern Dance Group (2015-March 2019). 

**_Emcee,_** UCLA Chinese Spring Festival Gala (2016-2018).
                                                            
\

## Skills

***

Microsoft Word/Excel/PowerPoint. Statistical applications including SAS and R. Programming in C++ and Python. Fluent Mandarin Chinese.

